
version: '3.3'

networks:
  default:
    external:
      name: network_default

volumes:
  mailserver_data:

services:
  mailserver:
    image: analogic/poste.io
    container_name: mailserver
    hostname: mail.${DOMAIN}
    restart: unless-stopped
    ports:
    - "25:25"
    - "110:110"
    - "143:143"
    - "587:587"
    - "993:993"
    - "995:995"
    - "4190:4190"
    environment:
      LETSENCRYPT_HOST: mail.${DOMAIN}
      LETSENCRYPT_EMAIL: ${USER_EMAIL}
      VIRTUAL_HOST: mail.${DOMAIN}
      VIRTUAL_HOST_NAME: "mail"
      HTTPS: "OFF"
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - /var/lib/docker/volumes/network_nginx_html/_data/.well-known:/opt/www/.well-known
    - mailserver_data:/data